# Generated by Django 5.1.1 on 2024-09-23 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_badge_guild_roleguild_customuser_elo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='guild',
            new_name='guild_id',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='role_guild',
            new_name='role_guild_id',
        ),
        migrations.RenameField(
            model_name='userbadge',
            old_name='badge',
            new_name='badge_id',
        ),
        migrations.RenameField(
            model_name='userbadge',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user_id', 'badge_id')},
        ),
    ]
