# Generated by Django 5.1.1 on 2024-09-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='return_type',
            field=models.CharField(default='int', max_length=255),
        ),
    ]
