# Generated by Django 5.1.1 on 2024-10-19 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeSystem', '0002_problem_return_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Fácil'), (2, 'Medio'), (3, 'Difícil')], default=1),
        ),
        migrations.CreateModel(
            name='UserSolverProblem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_solvers', to='codeSystem.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_solvers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
