# Generated by Django 5.1.1 on 2024-09-24 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeSystem', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_sets', to='codeSystem.problem')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_sets', to='rooms.room')),
            ],
        ),
    ]
