# Generated by Django 5.1.1 on 2024-10-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_problemset'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
