# Generated by Django 5.1.1 on 2024-10-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_description_alter_room_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed'), ('pending', 'Pending')], default='pending', max_length=100),
        ),
        migrations.DeleteModel(
            name='RoomStatus',
        ),
    ]
