# Generated by Django 5.1.1 on 2024-10-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_status_delete_roomstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemset',
            name='room_id',
        ),
    ]
