# Generated by Django 5.1.1 on 2024-10-15 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_remove_problemset_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemset',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='problem_sets', to='rooms.room'),
        ),
    ]
